config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies
  resources :genres
  resources :reviews, only: [:create]
  resources :reviewers 

  root "home#index"
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  validates :name, presence: true
  has_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :title, presence: true
  validates :genre, presence: true
  belongs_to :genre
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def show
    @movie = Movie.new
    @movies = @genre.movies.order(created_at: :desc)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      flash[:notice] = "Genre was successfully created"
      redirect_to genre_path(@genre)
    else
      flash.now[:error] = "An error occurred while saving this genre"
      render :new
    end
  end

  def edit
  end

  def update

    if @genre.update(genre_params)
      redirect_to genre_path(@genre), notice: "Genre was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this Genre"
      render :edit
    end
  end

  def destroy
    @genre.destroy

    redirect_to genres_path, notice: "Genre was successfully deleted"
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def find_genre
    @genre = Genre.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def show
    @review = Review.new
    @reviews = @movie.reviews.order(created_at: :desc)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @genre = Genre.find(params[:movie][:genre_id])

    if @movie.save
      redirect_to genre_path(@genre), notice: "Movie was successfully added"
    else
       flash.now[:error] = "An error occured while saving this movie"
       render 'genres/show'
    end
  end

  def edit
  end

  def update

    if @movie.update(movie_params)
      redirect_to movie_path(@movie), notice: "Movie was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this Movie"
      render :edit
    end
  end

  def destroy
    @movie.destroy

    redirect_to movies_path, notice: "Movie was successfully deleted"
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :genre_id)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
    
  def index
    @reviewers = User.all
  end

  def show
    @review = Review.new
    @reviews = @user.reviews.order(created_at: :desc)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_movie, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def create
    @review = Review.new(review_params)
    @movie = Movie.find(params[:review][:movie_id])
    @reviewer = User.find(params[:review][:user_id])
 
    if @review.save
      redirect_to movie_path(@movie), notice: "Review was successfully added"
    else
       flash.now[:error] = "An error occured while saving this review"
       render 'movies/show'
    end
  end
 
  private
 
  def review_params
    params.require(:review).permit(:title, :content, :movie_id, :user_id)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end

  def find_user
    @reviewer = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/genres/_form.html.erb
<%= form_for @genre do |f| %>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>

  <% if @genre.errors.any? %>
    <% @genre.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= link_to "Back to Genre List", genres_path %>

<%= render 'form' %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>

<%= link_to "Home", root_path %>

<% if current_user %>
  <%= link_to "Create New Genre", new_genre_path %>
<% end %>
<%= link_to "Click Here for Movie List", movies_path %>
<%= link_to "Click Here for Reviewer List", reviewers_path %>


<br />
<br />
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= link_to(genre.name, genre_path(genre)) %></td>

        <% if current_user %>
          <td><%= link_to "edit", edit_genre_path(genre) %></td>
          <td><%= link_to "delete", genre_path(genre), method: :delete, data: {confirm: "Are you sure you want to delete this genre?"}%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= link_to "Back to Genre List", genres_path %>

<%= render 'form' %>

app/views/genres/show.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>

<p><%= link_to "Back to Genre List", genres_path %></p>
<p><%= link_to "Click Here for Movie List", movies_path %></p>
<p><%= link_to "Click Here for Reviewer List", reviewers_path %></p>


<% if current_user %>
  <p><%= link_to "Create New Genre", new_genre_path %></p>
<% end %>


<p>
  <strong>Genre Name:</strong> <%= @genre.name %>
</p>

<% if current_user %>

<td><%= link_to "edit", edit_genre_path(@genre) %></td>

  <h3>Add a Movie</h3>
  <%= form_for @movie do |f| %>
    <p>
     <%= f.label :title %><br/>
     <%= f.text_field :title %>
    </p>

    <%= f.hidden_field :genre_id, value: @genre.id %>

    <%= f.submit %>

  <% end %>
<% end %>

<h3>Movies</h3>
 
<% @movies.each do |movie| %>
  <p>Title: <%= link_to(movie.title, movie_path(movie)) %></p>
  <hr/>
<% end %>

app/views/home/index.html.erb
<h1>Film Twitic</h1>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>


<p><%= link_to "Movies", movies_path %></p>
<p><%= link_to "Genres", genres_path %></p>
<p><%= link_to "Reviewers", reviewers_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Film Twitic</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="<%= name %>">
          <%= msg %>
        </div>

      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>

  <% if @movie.errors.any? %>
    <% @movie.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :genre %><br>
    <%= collection_select(:movie, :genre_id, Genre.all, :id, :name, include_blank: true) %>
  </p>

  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= link_to "Back to Movie List", movies_path %>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>

<%= link_to "Home", root_path %>

<% if current_user %>
  <%= link_to "Create New Movie", new_movie_path %>
<% end %>
<%= link_to "Click Here for Genre List", genres_path %>


  <br />
  <br />
  <table>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
    </tr>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= link_to(movie.title, movie_path(movie)) %></td>

          <% if current_user %>
            <td><%= link_to "edit", edit_movie_path(movie) %></td>
            <td><%= link_to "delete", movie_path(movie), method: :delete, data: {confirm: "Are you sure you want to delete this movie?"}%></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= link_to "Back to Movie List", movies_path %>

<%= render 'form' %>

app/views/movies/show.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>


<p><%= link_to "Back to Movie List", movies_path %></p>
<p><%= link_to "Click Here for Genre List", genres_path %></p>
<p><%= link_to "Click Here for Reviewer List", reviewers_path %></p>


<% if current_user %>
  <p><%= link_to "Create New Movie", new_movie_path %></p>
<% end %>

<p>
  <strong>Movie Title:</strong> <%= @movie.title %>
</p>

<p>
  <strong>Genre:</strong> <%= @movie.genre.try(:name) %>
</p>

<% if current_user %>

<td><%= link_to "edit", edit_movie_path(@movie) %></td>

  <h3>Add a Review</h3>
  <%= form_for @review do |f| %>
    <p>
     <%= f.label :title %><br/>
     <%= f.text_field :title %>
    </p>

    <p>
     <%= f.label :content %><br/>
     <%= f.text_area :content %>
    </p>

    <%= f.hidden_field :movie_id, value: @movie.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit %>

  <% end %>
<% end %>

<% if @review %>

<h3>Reviews</h3>
 
  <% @reviews.each do |review| %>
    <p>From: <%= review.user.email %></p>
    <p>Title: <%= review.title %></p>
    <p><%= review.content %></p>
    <p><%= review.created_at %></p>
    <hr/>
  <% end %>

<% end %>

app/views/reviewers/index.html.erb
<h1>Reviewers</h1>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>

<%= link_to "Home", root_path %>

<%= link_to "Click Here for Genre List", genres_path %>
<%= link_to "Click Here for Movie List", movies_path %>

  <br />
  <br />
  <table>
    <tr>
      <th>Username</th>
    </tr>
    <tbody>
      <% @reviewers.each do |reviewer| %>
        <tr>
          <td><%= link_to(reviewer.email, reviewer_path(reviewer)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/reviewers/show.html.erb
<h1>Reviewer</h1>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><span class="profile-email"><%= current_user.email %><span></li>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "register", new_user_registration_path %></li>
    <li> <%= link_to "sign in", user_session_path %></li>
  <% end %>
</ul>

<%= link_to "Home", root_path %>

<%= link_to "Click Here for Reviewers List", reviewers_path %>
<%= link_to "Click Here for Genre List", genres_path %>
<%= link_to "Click Here for Movie List", movies_path %>

<p>
  <strong>Username:</strong> <%= @user.email %>
</p>

<h3>Reviews</h3>
 
<% if @review %>

  <% @reviews.each do |review| %>
    <p>Movie Title: <%= review.movie.title %>
    <p>Review Title: <%= review.title %></p>
    <p><%= review.content %></p>
    <p><%= review.created_at %></p>
    <hr/>
  <% end %>

<% end %>